resources:
  - name: code
    type: git
    source:
      uri: https://github.com/chrisumbel/ConcourseTest
      branch: master


jobs:
  - name: build
    plan:
    - aggregate:
      - get: code
        trigger: true
    - task: compile
      privileged: true
      file: code/pipeline/compile.yml
    - task: test
      privileged: true
      file: code/pipeline/test.yml

