resources:
  - name: code
    type: git
    source:
      uri: https://github.com/chrisumbel/ConcourseTest
      branch: master


jobs:
  - name: build
    plan:
    - aggregate:
      - get: code
        trigger: true
    - task: dotnet
      privileged: true
      file: code/pipeline/dotnet.yml
